version: "3.3"

services: 
  api:
    image: flask-restplus
    container_name: autoseq_launcher_api
    build: .
    network_mode: host
    ports: 
      - 8100:8100
    user: 1009:1009
    volumes:
      - /nfs:/nfs
    environment:
      PORT: 8100
      FLASK_DEBUG: 1
